### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by krasnal21** [Err0r-ICA/JAR#2]
Username/Password ?

**Comment by qqqeeeltpda** [comment]
![Screenshot_20211221-085957.jpg](https://user-images.githubusercontent.com/95868452/146870183-b06cb5ab-d776-44bc-9776-6216533444ac.jpg)
What is the problem?

**Comment by blackrep4u** [comment]
What is the username and password

**Comment by Err0r-ICA** [comment]
DM: https://t.me/Err0r_HB
